package com.lv.greendao3.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lv.greendao3.model.Phone;
import com.lv.greendao3.model.User;

import com.lv.greendao3.model.PhoneDao;
import com.lv.greendao3.model.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig phoneDaoConfig;
    private final DaoConfig userDaoConfig;

    private final PhoneDao phoneDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        phoneDaoConfig = daoConfigMap.get(PhoneDao.class).clone();
        phoneDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        phoneDao = new PhoneDao(phoneDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Phone.class, phoneDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        phoneDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public PhoneDao getPhoneDao() {
        return phoneDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
