package com.lv.greendao3.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lv.greendao3.model.User;
import com.lv.greendao3.model.Phone;

import com.lv.greendao3.model.UserDao;
import com.lv.greendao3.model.PhoneDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig phoneDaoConfig;

    private final UserDao userDao;
    private final PhoneDao phoneDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        phoneDaoConfig = daoConfigMap.get(PhoneDao.class).clone();
        phoneDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        phoneDao = new PhoneDao(phoneDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Phone.class, phoneDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        phoneDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public PhoneDao getPhoneDao() {
        return phoneDao;
    }

}
